### ISSUE TITLE
Multiline title ?

### ISSUE THREAD

**Issue by erwanlr** [jfelchner/ruby-progressbar#103]
Is there a way to display the title of the progress bar on multiple lines ?

Said like that it would appear that it's not possible due to the new line characters, resulting in the bar being displayed below each one.

What I am trying to achieve is update the title to add a finding inside which should be displayed above the bar, with the reduced code below as example:

```ruby
require 'ruby-progressbar'

bar = ProgressBar.create(
  format: '%t %a <%B> (%c / %C) %P%% %e',
  title: 'Processing -',
  total: 5
)

5.times do |i|
  bar.increment

  bar.title = "Found: #{i}\n#{bar.title}" if i == 3

  sleep(1)
end
```

and would like an output like this:
```
Found: 3
Processing - Time: 00:00:04 <============> (5 / 5) 100.00% Time: 00:00:04
```

rather than the current one:
```
Found: 3ng - Time: 00:00:03 <======                      > (4 / 5) 80.00%  ETA: 00:00:01
Processing - Time: 00:00:04 <=====================> (5 / 5) 100.00% Time: 00:00:04
```

**Comment by jfelchner** [comment]
Sorry! That's not doable. The entire bar must be on one line or it won't be able to update properly.

**Comment by erwanlr** [comment]
Just found that the logging feature is exactly what I was trying to do and what I want ;o
