### ISSUE TITLE
Is it possible to trigger non-tty output manually?

### ISSUE THREAD

**Issue by axelson** [jfelchner/ruby-progressbar#109]
Looking at the documentation for [Non-TTY-Output](https://github.com/jfelchner/ruby-progressbar/wiki/Non-TTY-Output) I don't see a configuration option to force Non-TTY mode.

My use case is using the Fuubar formatter on CircleCI. It seems that the output that ruby-progressbar is able to see is TTY but then that output is being sent to the browser and too many lines are being sent.

**Comment by jfelchner** [comment]
@axelson I maintain fuubar as well.  The CircleCI folks have refused to set a `CONTINUOUS_INTEGRATION` environment variable in their containers which would allow this to be done automatically.  They have a `CI` environment variable, however, as fuubar is a popular gem, a `CI` environment variable is too ambiguous for me to rely on to disable TTY output.

If you want this to work for you, simply set `CONTINUOUS_INTEGRATION=true` in your `circle.yml` file and it'll work as you'd like.

**Comment by axelson** [comment]
Ah, ok. Thanks!
