### ISSUE TITLE
Warning instead of exceptions

### ISSUE THREAD

**Issue by gottfrois** [jfelchner/ruby-progressbar#110]
I don't think it's a good idea to raise exceptions in case of misconfigured progress bar (total for example). I have use cases where I set the total at run-time instead of at the beginning of my scripts. If for some reasons the total is not right, it raises a hard ruby exception, killing my process.

A warning log might be just as good and would not break running code.

**Comment by jfelchner** [comment]
I'm going to need some more information on your use case before I make a decision but if what you're saying is that you like to be able to set the total to something _less than_ the progress, the answer will almost certainly be "no". 

Basically every component of the bar depends on the total being >= the progress. If that's not the case, you'll still get an error somewhere else, it just won't be as well formatted. 

Additionally, it sounds like you're very unsure of what the total is, in which case `ruby-progressbar` has you covered. Just set the total to `nil` and increment the bar as usual. Once you know the total, set it at that point and everything will be as you expect. See "Unknown Progress" in the wiki for more details.

**Comment by gottfrois** [comment]
Thanks for the explanation, I figured I was missing the `total: nil`. Did not expect the total to be `100` by default :)
