### ISSUE TITLE
No method 'create' for ProgressBar:Class

### ISSUE THREAD

**Issue by dasibre** [jfelchner/ruby-progressbar#112]
I'm getting a no method error when calling create on ProgressBar. Both in repl and in ruby file. am i missing something?

**Comment by jfelchner** [comment]
Something else must be stepping on it.  Check your `Gemfile.lock` and make sure you don't have another progress bar library installed.

**Comment by dasibre** [comment]
Running ruby 2.1.2, on OSX Yosemite
using rvm 1.27.0
in irb console

2.1.2 :001 > require 'progressbar'
 => true 
2.1.2 :002 > ProgressBar.create
NoMethodError: undefined method `create' for ProgressBar:Class
	from (irb):2
	from /Users/james/.rvm/rubies/ruby-2.1.2/bin/irb:11:in `<main>'
2.1.2 :003 > 

I am to use ProgressBar.new without any issue.

**Comment by jfelchner** [comment]
That's the wrong progress bar gem. 

`require 'ruby-progressbar'`
