### ISSUE TITLE
build is failing according to readme

### ISSUE THREAD

**Issue by matkoniecz** [jfelchner/ruby-progressbar#113]
see https://github.com/jfelchner/ruby-progressbar#rubyprogressbar

**Comment by jfelchner** [comment]
I know this.  Thanks.  The gem works fine.

**Comment by matkoniecz** [comment]
In that case what is the point of this badge?

**Comment by jfelchner** [comment]
To show the status of the build.

**Comment by jfelchner** [comment]
Which happens to be failing.
