### ISSUE TITLE
%C with unknown progress should display '??'

### ISSUE THREAD

**Issue by bensomers** [jfelchner/ruby-progressbar#116]
The %C formatting option would be more useful (and much prettier) if it defaulted to '??' while progress was unknown. Happy to PR if it would be accepted - I'm guessing this change is trivial to implement.

**Comment by jfelchner** [comment]
@bensomers Wonderful!  Don't forget the test 😄

**Comment by jfelchner** [comment]
Closed in 3aab4711216dbc5e0e0787077cd906b89eab1fc9
