### ISSUE TITLE
Publish 1.8.2 version of ruby-progressbar

### ISSUE THREAD

**Issue by simonista** [jfelchner/ruby-progressbar#122]
You mention on the README that as of 1.8.2 the versions of progressbar and ruby-progressbar will be incremented in lockstep, but it doesn't seem like 1.8.2 ever got published to ruby-progressbar.  Am I misunderstanding something?

**Comment by jfelchner** [comment]
@simonista hahaha no, you're just very observant :)

FWIW 1.8.1 of `ruby-progressbar` is basically identical to `1.8.2` of `progressbar`  The `1.8.2` code for `progressbar` just had some CI fixes and one small change to make it build properly as either `progressbar` or `ruby-progressbar`.  These were purely under-the-hood changes.

Once I release the new version with the "total with unknown indicator", I'll update the README with the technically correct version at which the gems are in lockstep.
