### ISSUE TITLE
proposal:  Enumerator#with_progressbar

### ISSUE THREAD

**Issue by ronen** [jfelchner/ruby-progressbar#124]
Hi, i tried this out, it seems to work well, and makes it super-easy to use progressbar in the common simple cases:

```ruby
class Enumerator
  def with_progressbar(**args, &block)
    chain = Enumerator.new do |y|
      progressBar = ProgressBar.create(**{total:size}.merge(args))
      each do |*args|
        (y.yield *args).tap { progressBar.increment }
      end
    end
    if block_given?
      chain.each &block
    else
      chain
    end
  end
end
```

usage of course:

```
things.each.with_progressbar { |thing| ...  }  # vanilla
things.map.with_progressbar(title: "Comprehension") { |thing| ... }
things.each.with_progressbar.with_index(title: "Enumerator chaining") { |thing, i| ... }
```

~If this is something you'd accept I could put together a formal PR (I'd need to figure out how to put together proper specs for it).  Or feel free to just grab the code and insert it yourself.~  Update: In for a penny, in for a pound...  I added specs and submitted PR #125
 
BTW this ought to work with unbounded/lazy enumerations, they'd have `size: nil` so would get Unknown Progress behavior.  Of course this doesn't give access to the ProgressBar object, so can't do fancy things like changing or logging or whatnot; in those cases one would need go back to creating and using the ProgressBar manually

**Comment by ronen** [comment]
As mentioned in the PR, this only works when `Enumerator` and `Enumerator#size` are defined, i.e. ruby > 1.9; the code guards for those and is a no-op if they're not defined.

**Comment by jfelchner** [comment]
Closing this in favor of the PR.  @ronen I haven't forgotten about you 😉
