### ISSUE TITLE
Easy finishing a progress

### ISSUE THREAD

**Issue by gudata** [jfelchner/ruby-progressbar#133]
In some cases it is ok to go over the total_items.

In my case I am tracking time. I iterate from start to end via @step .

```
progressbar = ProgressBar.create(:title => "History", :starting_at => 0, :total => @end_date.to_i - @start_date.to_i)
loop do
   (progressbar.progress + @step > progressbar.total) ? progressbar.progress = progressbar.total :  progressbar.progress += @step

```

simple
```
 progressbar.increment @step 
```

will work.

**Comment by jfelchner** [comment]
I have absolutely no idea what you're talking about 😂

If you don't know the total, just set it to `nil` until you know the total.

**Comment by gudata** [comment]
I know the total.
I know the increment
I know the start value
on the final loop when I try to increment the progressbar, the progressbar complains that I can't because the value will become above the total.

**Comment by jfelchner** [comment]
Then why don't you set the total to that value to begin with?

**Comment by gudata** [comment]
You tell me.

I am working with seconds

0 -------Start----(step)------Total

If I do it I will see that 99% of the time has passed because I am on the far right of the time. And the time starts from 0.

**Comment by jfelchner** [comment]
I might be a language barrier thing but what you're saying isn't making sense to me.  You're saying two different things.

You said:

* I know the start value (presumably `@start_date.to_i`)
* I know the total (presumably `@end_date.to_i - @start_date.to_i`)
* I know the increment (presumably `@step`)

This works:

```ruby
step = 9
start_date = Time.utc(2013, 1, 1, 0, 0, 0).to_i
end_date = Time.utc(2015, 1, 1, 0, 0, 0).to_i
progressbar = ProgressBar.create(:title => "History", :starting_at => 0, :total => end_date - start_date)

begin
  progressbar.progress += step
end while !progressbar.finished?
```

So what is the problem?

**Comment by gudata** [comment]
You are putting the progress bar as part of the main logic.
The progress bar is just a supplementary tool to display some progress bar. if I have it - ok. If I don't - ok.

I have much complex loop and step but for example, I am using it in the following way.

```
step = 9
from = 0
to = 123
i = 0
progressbar = ProgressBar.create(:title => "History", :starting_at => from, :total => to)
while i < to do
  i += step
  progressbar.progress += step
end 
```

It should be totally fine the last step to be above the total. 

Once again: progress bar is just a helper it should not raise errors. Imagine if your logger raises an errors. Logger::MessageToShortError ...MessageNotEnoughDescriptive..... 

Again in this tone the initialization is way too heavy....
I have a method with 3 lines and the init of the progressbar is 9 !

````
      progressbar = ProgressBar.create(
        title: "History",
        starting_at: 0,
        total: @end_date.to_i - @start_date.to_i,
        format: "%a %e %b\u{15E7}%i %p%% %t",
        progress_mark: ' ',
        remainder_mark: "\u{FF65}",
      )

````

Also, I don't understand why such a wonderful and easy to work gem was merged into this heavy to work and so restricting progress bar.

**Comment by jfelchner** [comment]
@gudata show me what the initialization would have looked like to get the same bar with the old `progressbar` codebase 😏

As far as this continued insistence that the bar shouldn't throw an error:

```ruby
pb = ProgressBar.create(starting_at: 90, total: 100)
pb.progress += 20

pb.progress # => 100  <-- This is incorrect (the user specified they wanted a progress of `110`)
pb.progress # => 110  <-- This is *also* incorrect (the progress is greater than the total the user requested)
```

In the above example we _cannot assume_ what the user wanted to do.  They may have wanted to set the progress to the total but they _may also_ have _made a mistake._

In your example all you have to do is to do what I described above:

```ruby
step = 9
from = 0
to = 123
i = 0
progressbar = ProgressBar.create(:title => "History", :starting_at => from, :total => to)

begin
  progressbar.progress += step
rescue ProgressBar::InvalidProgressError
  progressbar.finish
end while !progressbar.finished?
```

**Comment by jfelchner** [comment]
And for the record, your `Logger` example is not even remotely the same thing.  Logging a message of `"a"` doesn't throw an error `MessageTooShort` because `"a"` is a valid log message.  A progress above the total is not a valid progress.
