### ISSUE TITLE
Access percentage easily

### ISSUE THREAD

**Issue by AliEskandari** [jfelchner/ruby-progressbar#134]
## Current Behavior
Getting the percentage completed from the progressbar instance is not possible, or easy.
```
progressbar.progress # => 1
progressbar.percentage
# => NoMethodError Exception: protected method `percentage' called for #<ProgressBar:1/187>
```

## Expected Behavior or New Behavior
```
progressbar.progress # => 1
progressbar.percentage # => 1 or .01 or "1%"
```

### Context 

I would like to log the progress to a rails log file (development.log, or production.log) only when the percentage is a multiple of 10 (at 10%, 20%..). To do this I need the percentage, otherwise I calculate the percentage myself.

```
logger.info(progressbar) if (progressbar.progress*100/progressbar.total) % 10 == 0
# would like to do:
logger.info(progressbar) if progressbar.percentage % 10 == 0
```

**Comment by jfelchner** [comment]
I think this seems reasonable to me. 👍🏻

**Comment by kochka** [comment]
Hello,

Would be also cool to put the timer public for the same reason (I use it to log elapsed time to file for example) or to add a method in the public api to get elapsed time.

Cheers

**Comment by jfelchner** [comment]
@kochka @AliEskandari I decided to go with [a more general solution](https://github.com/jfelchner/ruby-progressbar/commit/84a6b9c197c7d431a4ffd2dbe4c9d697ad06e4f2) so that I didn't have to start exposing a bunch of accessors.  Once 1.9 is released you can call `to_h` on your progressbar instance to get access to most of the different pieces of information.  Here is an example hash:

```ruby
{
  'output_stream'                       => #<StringIO:0x007fdf2d056928>,                                                                                                                                                                                                                           |  ETA: ??:??:??
  'length'                              => 92,
  'title'                               => 'My Title',
  'progress_mark'                       => 'x',
  'remainder_mark'                      => '-',
  'progress'                            => 22,
  'total'                               => 33,
  'percentage'                          => 66.66,
  'elapsed_time_in_seconds'             => 599.99994701264,
  'estimated_time_remaining_in_seconds' => 400,
  'base_rate_of_change'                 => 0.03672787979966611,
  'scaled_rate_of_change'               => 7.345575959933222,
  'unknown_progress_animation_steps'    => ['=---', '-=--', '--=-', '---='],
  'throttle_rate'                       => 12.3,
  'started?'                            => 2012-07-26 12:50:00 -0500,
  'stopped?'                            => false,
  'finished?'                           => false
}
```

Hope this helps.
