### ISSUE TITLE
Decrementing progress with non-TTY output causes NoMethodError

### ISSUE THREAD

**Issue by lowjoel** [jfelchner/ruby-progressbar#139]
## Current Behavior
Decrementing progress (or calling `#reset`, which is what I'm actually trying to do) seems to cause a NoMethodError when running under a non-TTY output (such as when running RSpec within IntelliJ)

I seem to gather from the wiki that decrementing should be a supported operation.

### Steps to Reproduce 

Given this code snippet:
```ruby
irb(main):011:0> p = ProgressBar.create(output: File.open('test.out', 'w'))
=> #<ProgressBar:0/100>
irb(main):012:0> 10.times { p.increment }
=> 10
irb(main):013:0> p.decrement
=> #<File:test.out>
irb(main):014:0> p.decrement
NoMethodError: undefined method `+' for nil:NilClass
        from /Users/joellow/Development/git-splice/vendor/ruby/2.4.0/gems/ruby-progressbar-1.9.0/lib/ruby-progressbar/output.rb:64:in `print_and_flush'
        from /Users/joellow/Development/git-splice/vendor/ruby/2.4.0/gems/ruby-progressbar-1.9.0/lib/ruby-progressbar/output.rb:51:in `block in refresh'
        from /Users/joellow/Development/git-splice/vendor/ruby/2.4.0/gems/ruby-progressbar-1.9.0/lib/ruby-progressbar/throttle.rb:22:in `choke'
        from /Users/joellow/Development/git-splice/vendor/ruby/2.4.0/gems/ruby-progressbar-1.9.0/lib/ruby-progressbar/output.rb:48:in `refresh'
        from /Users/joellow/Development/git-splice/vendor/ruby/2.4.0/gems/ruby-progressbar-1.9.0/lib/ruby-progressbar/output.rb:44:in `with_refresh'
        from /Users/joellow/Development/git-splice/vendor/ruby/2.4.0/gems/ruby-progressbar-1.9.0/lib/ruby-progressbar/base.rb:177:in `update_progress'
        from /Users/joellow/Development/git-splice/vendor/ruby/2.4.0/gems/ruby-progressbar-1.9.0/lib/ruby-progressbar/base.rb:89:in `decrement'
        from (irb):14
        from /usr/local/bin/irb:11:in `<main>'
irb(main):015:0> p.progress
=> 8
```

## Expected Behavior

I think this should work without raising an error.

**Comment by jfelchner** [comment]
@lowjoel so here's the issue with decrementing with non-TTY output.  Due to the way non-TTY devices work, we can't delete part of the bar like we can with TTY.  So even if the bar should technically show fewer progress marks after decrementing, we have to leave it where the bar currently is, which could be confusing.  Of course it would also be valid to argue that not allowing decremeting is confusing 😂

What are your thoughts around the bar potentially not showing the correct bar length for the value currently stored in the bar?

**Comment by lowjoel** [comment]
I think it is OK if the length is wrong on non-TTY outputs, but raising an exception is a little harsh. This makes the program fail just by piping output to file.

Thoughts?

**Comment by jfelchner** [comment]
@lowjoel a solution to this that is acceptable to me is in PR #147 

I'll merge this in a week or so.

**Comment by lowjoel** [comment]
awesome! thanks!
