### ISSUE TITLE
When using null outputter, to_s always returns empty string

### ISSUE THREAD

**Issue by gondalez** [jfelchner/ruby-progressbar#140]
Relates to #131 and [this wiki entry](https://github.com/jfelchner/ruby-progressbar/wiki/Null-(Blackhole)-Output).

Any ideas @jfelchner? 
(and thanks for the feature in the first place!) 😌 

## Current Behavior
When using `ProgressBar::Outputs::Null`, `to_s` always returns empty string.

### Steps to Reproduce 
Using ruby 2.4.1 and ruby-progressbar 1.9.0:
```
irb
irb(main):001:0> require 'ruby-progressbar'
=> true
irb(main):002:0> require 'ruby-progressbar/outputs/null'
=> true
irb(main):003:0> progressbar = ProgressBar.create(output: ProgressBar::Outputs::Null)
=> #<ProgressBar:0/100>
irb(main):004:0> progressbar.progress += 10
=> 10
irb(main):005:0> progressbar.to_s
=> ""
```

## Expected Behavior or New Behavior
I would love it if `to_s` returned the progress bar as it does without specifying the null outputter below.
In my use case it would be nice to disable TTY and periodically write an update with ETA to a log.
```
irb(main):006:0> progressbar = ProgressBar.create
=> #<ProgressBar:0/100>                                                                                                                                      |
irb(main):007:0> progressbar.progress += 10
=> 10ess: |==============                                                                                                                                    |
irb(main):008:0> progressbar.to_s
=> "Progress: |==============                                                                                                                                    |"
```

**Comment by jfelchner** [comment]
@gondalez just got to this.  Let me dive in and take a look.  It might be a few days.

**Comment by jfelchner** [comment]
@gondalez I'm not finding a quick solution to this unfortunately.

**Comment by jfelchner** [comment]
@gondalez I'd love to do this for you, but I just don't think it's possible without a substantial amount of work.  I just don't have the time for what amounts to a very specialized use case.  I'm sorry. 😔
