### ISSUE TITLE
Only output the error "You can't set the item's current value to greater than the total" once?

### ISSUE THREAD

**Issue by jstumbaugh** [jfelchner/ruby-progressbar#141]
I love using this progress bar. It's super helpful for monitoring the progress of the CSV imports that I use all the time. As expected, if you increment the progress bar to a value greater than the total specified, you get the following notification: 

```
#<ProgressBar::InvalidProgressError: You can't set the item's current value to be greater than the total.>
```

However, it outputs this message each time you increment it after. I was wondering if it would be desirable to only show this message *once*, rather than each time the progress bar is incremented.

I would be more than happy to submit a PR for that capability, but I want to know if that would be something that people would want, or if the error message outputted each time is the desired behavior.

(Yes I also realize that I could set the correct total initially :sweat_smile:)

**Comment by jfelchner** [comment]
@jstumbaugh what I would suggest instead is _not_ setting the total.  If `total` is set to `nil`, then you'll get an [unknown progress bar](https://github.com/jfelchner/ruby-progressbar/wiki/Unknown-Progress).  As soon as you want to set the total, you can do that and it will "snap" into place as you would expect.

Hope this helps!
