### ISSUE TITLE
How to use `create_images.rb`?

### ISSUE THREAD

**Issue by martin-eden** [jfelchner/ruby-progressbar#142]
Hello,

I wish to run `create_images.rb` file. 

I'm doing
```
$ ruby create-images.rb
```
and getting
```
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- progress-bar (LoadError)
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from create-images.rb:2:in `<main>'
```

What is wrong? 

Ruby version: `ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]`

**Comment by jfelchner** [comment]
@martin-eden this isn't an issue with the progress bar gem, it's an issue with your script.

**Comment by martin-eden** [comment]
Whoops. Sorry, created issue in wrong repository.
