### ISSUE TITLE
Rubygems link to the documentation is broken

### ISSUE THREAD

**Issue by belgoros** [jfelchner/ruby-progressbar#143]
Just FYI, the link `http://0xcc.net/ruby-progressbar/index.html.en` provided in the [rubygems](https://rubygems.org/gems/progressbar) site is broken.

**Comment by jfelchner** [comment]
Thanks @belgoros!  This is fixed in c1a2e5c90a1b84d8495f3c7bb81c62ea761faa99 and will go out with the next release.
