### ISSUE TITLE
Feature Request - Store log messages for later retrieval

### ISSUE THREAD

**Issue by erwanlr** [jfelchner/ruby-progressbar#144]
When using the Null output along with #log, the messages are sent into the void and can't be retrieved for later usage.

I was going to monkey patch the Outputs::Null class to the below one:

```ruby
class ProgressBar
  module Outputs
    # Adds the feature to log messages sent to #log
    # So they can be retrieved at some point, like after a password attack with a JSON output
    # which won't display the progressbar but still call #log for errors etc
    class Null < Output
      # @retutn [ Array<String> ]
      def logs
        @logs ||= []
      end

      # Override of parent method
      def log(string)
        logs << string
      end
    end
  end
end
```

However, to be able to access the #logs, I would also have to monkey patch the ProgressBar::Base to delegate the #logs to :output. Quite a messy thing to do. Even with a custom output class, the #logs could not be accessed properly as the ProgressBar#output is protected (could still use bar.send(:output) but that's ugly)

So, I was wondering if it would be possible to implement a storage the messages sent to #log (regardless of the Output), and be able to retrieve them with a #logs method.

**Comment by jfelchner** [comment]
@erwanlr first off, you don't have to monkey patch anything.  The outputters are designed to be extensible.  So you should do:

```ruby
class MyOutput < ::ProgressBar::Outputs::Null
  # Code
end

progressbar = ProgressBar.create(output: MyOutput)
```

Secondly, what I would be doing instead is, in your custom code, send the logs wherever you want yourself:

```ruby
class MyOutput < ::ProgressBar::Outputs::Null
  def log(string)
    File.write('myfile.log', string)
  end
end
```
