### ISSUE TITLE
Defaults for tty and no_tty output are different

### ISSUE THREAD

**Issue by gizmomogwai** [jfelchner/ruby-progressbar#145]

**Comment by jfelchner** [comment]
I’ll reopen this once you give me more information with examples.

**Comment by gizmomogwai** [comment]
I am referring to
https://github.com/jfelchner/ruby-progressbar/blob/4c770c2b1847c356a7d2081c7de24f885697371e/lib/ruby-progressbar/outputs/tty.rb#L6

and 

https://github.com/jfelchner/ruby-progressbar/blob/4c770c2b1847c356a7d2081c7de24f885697371e/lib/ruby-progressbar/outputs/non_tty.rb#L6


The fact that the default are different is not a big problem, because i guess most people customise anyways. Still I so love this gem, that I looked into the source, and I just wondered, why the difference is there, and if its on purpose. The only thing that comes to mind is, that this is a little bit code duplication, but perhaps this duplication is better than to couple the modules in any way.

So please keep it considered closed if that not a problem for you :)

Btw. one of my favourite gems!

**Comment by jfelchner** [comment]
@gizmomogwai thanks for the extra information!  It's like that on purpose.  See [the wiki article](https://github.com/jfelchner/ruby-progressbar/wiki/Non-TTY-Output).

**Comment by jfelchner** [comment]
I'm glad you like the gem!

**Comment by gizmomogwai** [comment]
Wow thanks .. again something learned :)
