### ISSUE TITLE
Ability to host gem on internal gem server

### ISSUE THREAD

**Issue by ulag** [jfelchner/ruby-progressbar#151]
## Current Problem
In our environment, we host all public gems on an internal gem server to facilitate better control on what gems are used by our teams. So a developer typically downloads a public gem and submit it for approval. whoever approves the gem will push the gem to our private gem server and all our dev and deploy tooling will always use private gem server as "source" for any gems.

When we try to do it with ruby-progressbar gem, it doesn't let us push this gem to our private gem server. this gem has the "allow_push_host" limitation to ruby gems alone. From what we understand, the "allow_push_host" is used to control accidental pushes of private gems to public gem servers like rubygems.  But looks like here you are using to prevent people from hosting this on their private serves. Is this done for some specific security issue? Is it possible for us to host it on our internal server?

**Comment by jfelchner** [comment]
@ulag You're right, I'll remove this for you.

**Comment by ulag** [comment]
thank you @jfelchner
