### ISSUE TITLE
Default options

### ISSUE THREAD

**Issue by romanbsd** [jfelchner/ruby-progressbar#155]
## Current Problem
I'm finding myself using the same options over and over again:
PB_OPT = { length: 80, format: '%a |%B| %p%% %c/%C' }

## Potential Solution or New Behavior
It would be nice if it was possible to define default options.

### Mockups
Something like:
```ruby
ProgressBar.defaults = { length: 80, format: '%a |%B| %p%% %c/%C' }
```

**Comment by jokklan** [comment]
I would love this feature as well. I also find my self using the same format again and again. I even sometimes make a "proxy class" for ruby progressbar so I don't have to specify the options for each instance.

**Comment by jfelchner** [comment]
@romanbsd length can already be overridden with an environment variable.  I will consider doing the same thing for the format string.

**Comment by gurgeous** [comment]
Love the gem, thank you for continuing to work on it.

Yes, default options please! I added the following monkeypatch to our project. Then I was able to clean up over twenty scripts...

```ruby
# use our default format for ruby-progressbar
class ProgressBar::Outputs::Tty
  def default_format
    '%t %p%% |%B| %e   '
  end
end
```

**Comment by jfelchner** [comment]
@gurgeous thanks!  I'll probably add this for the format soon.

**Comment by jfelchner** [comment]
Added this for you all: https://github.com/jfelchner/ruby-progressbar/commit/312db6b328551a4337b4bc482f748c1683fd31db

Apologies for the delay.  It'll go out with the next release.  Thank you all for your patience.

I also updated the [wiki page](https://github.com/jfelchner/ruby-progressbar/wiki/Formatting) with information about the new environment variable.

**Comment by gurgeous** [comment]
No need to every apologize for an open source delay. I understand completely and I appreciate your hard work :)

**Comment by jfelchner** [comment]
@gurgeous I appreciate it and you just caught me!  I was about to post back to recent issues to let everyone know that `1.11.0` has just been released :))
