### ISSUE TITLE
Enumerable class which takes enumerable 

### ISSUE THREAD

**Issue by ytti** [jfelchner/ruby-progressbar#156]
More a question, than feature request.

## Current Problem
  You need special class to have progress bar on it, which also needed refinements, it's not entirely obvious to me why this was first solution and only solution for automatic progressbar.

## Potential Solution or New Behavior
Allow wrapping any enumerator with enumerator which emits progressbar

### Mockups
```ruby
  require "io/console"
  class Progress
    include Enumerable
    def initialize(enumerable)
      @enumerable = enumerable
      @output_every = (@enumerable.size / IO.console.winsize.last.to_f).to_i+1
    end
    def each
      @enumerable.each_with_index do |item, index|
        print "=" if index % @output_every == 0
        yield item
      end
      print "\n"
    end
  end

  can_has_pb = true
  thing = (1..10000)
  enum = can_has_pb ? Progress.new(thing) : thing
  enum.each do |l|
    sleep 0.0001
    l
  end
```

The notion is, that use case commonly is CLI, and you commonly have way to disable progress bar(s) and you have what ever enumerables you have, which sometimes you want to use with progress bar sometimes you don't want to.

I may miss something obvious, but it seems this call type would be very desirable requiring no dirty deeds.

**Comment by jfelchner** [comment]
I don't consider refinements "dirty".  I was against them when Ruby first introduced them, but they're here, they work fairly well, and they're not going anywhere.

Additionally your example is extremely simple and leaves out a ton of edge cases.  If you were to add in everything `ruby-progressbar` has to deal with into that example, it would be massive and a ton of duplication.

For now, refinements are the way we're dealing with this issue.  Without them, this behavior wouldn't be supported at all.

https://github.com/jfelchner/ruby-progressbar/wiki/Using-Enumerators
