### ISSUE TITLE
In non-TTY mode, using `to_s` with a format argument does not change the format of the returned string

### ISSUE THREAD

**Issue by jornvandebeek** [jfelchner/ruby-progressbar#157]
## Current Behavior
In non-TTY mode, using `progressbar.to_s` with a format argument does not change the format of the returned string 

### Steps to Reproduce

1. Trigger non-tty mode by specifying a null file output:
 `progressbar = ProgressBar.create output: File.open(File::NULL, "w")`
 (`ProgressBar::Outputs::Null` does not exhibit the bug)
3. `progressbar.to_s('%E')` returns `Progress: ||`

## Expected Behavior
 `progressbar.to_s('%E')` returns ` ETA: ??:??:??`

## Fix

I think https://github.com/jfelchner/ruby-progressbar/blob/master/lib/ruby-progressbar/outputs/non_tty.rb#L36 needs a `yield` inside?

**Comment by jornvandebeek** [comment]
Note that for suppressing output, one should really use [`ProgressBar::Outputs::Null`](https://github.com/jfelchner/ruby-progressbar/wiki/Null-(Blackhole)-Output) and not  `File.open(File::NULL, "w")`. The latter is really slow for some reason, I have only used it here to trigger non-tty mode to showcase the bug.

**Comment by jfelchner** [comment]
This is fixed in https://github.com/jfelchner/ruby-progressbar/commit/619276a698e00bc8fa1c6f29ee4dba79b5490b26

@jornvandebeek apologies for the delay.  It'll be out in the next release.  Your reproduction steps and fix were 100% on the money.  Thank you for taking the time to leave a detailed message. ❤️

**Comment by jfelchner** [comment]
Sorry for the delay in this @jornvandebeek. I pushed a fix and then realized it wasn't correct.  Non-TTY devices are not able to change their formatting.  They are effectively "set" to a default and cannot be changed.  You can read more about it here: https://github.com/jfelchner/ruby-progressbar/wiki/Non-TTY-Output

I'm so sorry it took me so long to get back to this issue just to tell you that it isn't possible to fix.

Your suggestion of adding the `yield` does indeed fix this _particular_ issue, but for a non-TTY device, it's not going to and up doing what you want it to do. :(

If you have a particular use case that you can describe to me in more detail, I might be able to help you with a custom `Output` object.
