### ISSUE TITLE
worst.manual.ever

### ISSUE THREAD

**Issue by okliv** [jfelchner/ruby-progressbar#158]
Man, it is just progress bar. Your wiki structure is like it is complex multifunctional library. While it is possible to write (I guess) a short article to describe 90% of all functionality just in 3(?) minutes of reading of flat page rich example, you propose us to surf like 5.viii complex parts and even more!

you can delete this issue. there is nothing to discuss (as for me). just my humble opinion.

**Comment by jfelchner** [comment]
Thank you for the feedback.
