### ISSUE TITLE
Embeding textual message in progress

### ISSUE THREAD

**Issue by sdalu** [jfelchner/ruby-progressbar#162]
## Current Problem
It's not possible to have textual progress information inside the progress bar

## Potential Solution or New Behavior
With perhaps a new method for updating like:
```ruby
progressbar.update(:msg => "Processing file foo", :increment: 1)
```

### Mockups
```
Progressing file foo  : |=====================                               |
Removing file bar     : |===============================                     |
Adding file toto      : |===================================                 |
```

**Comment by jfelchner** [comment]
It [is possible to do this.](https://github.com/jfelchner/ruby-progressbar/wiki/Options)  You just have to change the title of the bar.
