### ISSUE TITLE
Is there any way to use `log` when using `with_progressbar`?

### ISSUE THREAD

**Issue by quetzalcoatl** [jfelchner/ruby-progressbar#163]
Basically - as in the title.

If I'd want to print out something and still have the progressbar, I could use the `bar.log` method, but .. I apparently don't have any reference to the `bar`. According to the wiki, `with_progressbar` passes only the visited items from enumerable.

If there's really no way to do that now, then maybe it could be added, for example as passing the reference to the current ProgressBar object as tail to the block params? That way something like this could be possible:

```
    [[1,2],[3,4],[5,6]].each.with_progressbar() do |n, m, bar|
      #puts "yay: #{n}" if m == 4   -- puts damages the output
      bar.log "yay: #{n}" if m == 4
      sleep 0.05
    end
```

EDIT: now thinking about it, it's handy only in cases with the automatic array-to-params expansion.. if someone doesn't use it, and takes array as an array, then appending the `bar` would mess up array's contents? In that case, "appending extra `bar`" parameter would need to be switchable by options... what a mess. I think I'll stick with full PB.create/increment/finish flow. In the meantime, I'm leaving this open, maybe someone knows a way to print-out safely while in with_progressbar?

**Comment by jfelchner** [comment]
@quetzalcoatl thanks for the issue!  Yeah it might be handy in certain cases, but I think I'm going to leave it out for now.

Thank you!
