### ISSUE TITLE
Incorrect ETA calculation if starting_at

### ISSUE THREAD

**Issue by senhalil** [jfelchner/ruby-progressbar#164]
## Current Behavior

The following process launched with 195 items already launched -- i.e., `{ starting_at: 195 }`.

```bash
Time: 00:22:35  ETA: 15:20:16 Progress: 80.40% Launched: 201 of 250
```

Even though 6 items took 22:35 -- i.e., 3.67 minutes per item -- the calculated ETA is 15+ hours. Which suggests me that ETA is calculated with total number of items (3.67 * 250 ~= 15 hours) instead of remaining number of items -- but didn't dig into the code.

### Steps to Reproduce

Here is an MWE

```ruby
require 'ruby-progressbar'

progressbar = ProgressBar.create(
	total: 100,
	starting_at: 90, 
	smoothing: 0, # for ease of demonstration
	format: "%a %e Progress: %P% Launched: %c of %C"
)

10.times.each{
	sleep(6) 
	progressbar.increment
}
```

## Expected Behavior
In the MWE, since there were 10 items to go at the very beginning, the first ETA should be 54 seconds (6 x (100 - 90) - 6) and evolve from that but it starts from 9:54 -- (6 x (100) - 6).

## Environment

ruby --version
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux]

**Comment by jfelchner** [comment]
Ah interesting!  Let me take a look!  Thanks.  Especially for the pseudocode! ❤️

**Comment by senhalil** [comment]
No worries! Happy to be of help. I should be thanking you for the gem! <3

By the way, I observed a similar issue even with `starting_at: 0`. I believe two issues are related. 

With smoothing completely turned off, my expectation was that there is no smoothing and that the remaining time is calculated with the last item's duration (x remaining number of items); however, I think the approximate time is still smoothed (in the mathematical sense) with the previous item by using the average time (because ETA is calculated by "scaling" the past time). 

However, if the iteration/item duration has a (increasing/decreasing) trend then the ETA is always behind or infront of the actual time.

For example, in the following, ETA is always behind but more importantly the last iteration's ETA is 5 seconds, but the previous iteration was 9 seconds -- this difference can be arbitrarily large (in my case 10+ hours).
```ruby
progressbar = ProgressBar.create(total: 10, starting_at: 0, smoothing: 0,format: "%a %e Progress: %P% Launched: %c of %C")
10.times.each{ |i| sleep(i+1); progressbar.increment }
```

Basically averaging is a form of smoothing in its own right and it assumes that there is no trend in the data and each item's duration is uniformly distributed. The last assumption is strong and when it doesn't hold, it leads to incorrect ETA estimation. 

I checked the code very quickly and if I understand it correctly, the smoothing is applied to running average (the percentage) and ETA is calculated as follows:
```ruby
def estimated_seconds_remaining
  (timer.elapsed_seconds * (progress.total / progress.running_average - 1)).round
end
```
where
```ruby
    self.running_average = Calculators::RunningAverage.calculate(running_average,
                                                                 absolute,
                                                                 smoothing)
```
but this obscures the smoothing operation. 

If the ETA was calculated as `estimated_average_item_duration X number_of_items_left` and if the smoothing was applied to the "average item duration" itself then the ETA calculation would show the smoothing operation more transparently as follows:

```ruby
def estimated_seconds_remaining
   ((progress.total - progress.progress) * Calculators::RunningAverage.calculate(running_average_item_duration,
                                                                                 last_item_duration,
                                                                                 smoothing)).round
end
```

**Comment by jfelchner** [comment]
@senhalil I think I have a commit which solves your issue: https://github.com/jfelchner/ruby-progressbar/commit/1cea7986334c352e61d5b0efeaf703d3b5160fee. I updated the tests to pass without actually checking to see if that's the behavior I want, but I wanted to verify with you that this is what you were looking for.

Unfortunately doing the calculation you suggested is not going to work as tracking per-item durations would be far too complex since users can not only decrement the bar, but also arbitrarily move it to any position they choose.

In fact, even this solution breaks down if that happens, however since starting at a spot and moving forward is the 99% use case, I'm ok with optimizing the estimated time for that case.

I'd love it if you could check out that commit with Bundler and verify that it seems to work better for you.

And sorry for the delay on getting to this.

**Comment by senhalil** [comment]
Hi @jfelchner cheers for taking the time for the fix. I am afraid I am focused on another subject at the moment and it might take me a while to get back to the other project. However, I read the test and it looks good to me. It fixes the main issue explained in this ticket (i.e., starting_at leads to incorrect estimation). If you are happy with the behavior as well, I think no reason to keep this ticket open. 

I see your concern about tracking per-item duration being too complex. What I originally had in mind was mathematically equivalent to what is currently done most of the time but it was just a change of perspective which would lead to improved estimation under certain corner cases but the memory is vague. I will try and create a feature request with pseudo-code (or better a PR) when I return the other project and restart using ruby-progressbar.

Season’s Greetings! And best wishes for the New Year.

**Comment by jfelchner** [comment]
Happy Holidays to you as well!

That sounds fantastic and no worries if you can't get back to it, but I definitely think I would need a PR (even if it doesn't entirely work) to get a better sense of what you're talking about.

I'm going to close this out for now and we can revisit the other improvement in another issue. :)

**Comment by jfelchner** [comment]
@senhalil version `1.11.0` has just been released :))
