### ISSUE TITLE
Use `Logger` class with `ProgressBar#log`

### ISSUE THREAD

**Issue by DonIsaac** [jfelchner/ruby-progressbar#169]
Current Problem
--------------------------------------------------------------------------------

I'm interested in adding `ruby-progressbar` into an existing project, but it is incompatable with our current logging implementation. We use the [built-in Ruby Logger](https://ruby-doc.org/stdlib-2.7.0/libdoc/logger/rdoc/Logger.html) to control formatting and log levels, and there seems to be no way to integrate this with `ProgressBar#log`

Potential Solution or New Behavior
--------------------------------------------------------------------------------

```ruby
require 'logger'
require 'ruby-progressbar'

bar = ProgressBar.create
bar.log.level =  Logger::INFO

bar.log "foo" # prints "foo" to STDOUT using default log level (probably info)
bar.log.debug "message" # print a message with a desired log level
bar.log.warn("progname") { "a warning message" } # specify program name
```

**Comment by jfelchner** [comment]
`.log` is designed as a convenience method to output some text onto the screen and then to have the bar redraw itself below that.  It is not meant in regards to "log" like "log file".  There is no mechanism to have `.log` go to a different output stream than the bar itself.

If you want to log to a file, then you should just do that by passing in a reference to your log implementation.  For more info on how logging works with the bar, you can see the wiki article [here](https://github.com/jfelchner/ruby-progressbar/wiki/Logging).
