### ISSUE TITLE
Bar refuses to update on the first increment

### ISSUE THREAD

**Issue by pedrofoliveira** [jfelchner/ruby-progressbar#174]
Hi,
I'm trying the code below but the bar does not seem to update on the first increment! Am I missing something? (probably am)

```ruby
bar = ProgressBar.create(:title => "Progress:", :total => 15, :remainder_mark => '.', :length => 100, :format => '%t: (%c/%C) %W %E')
5.times do |x|
  bar.increment
  puts bar.to_h
  sleep 1
end
puts "\nDone!"
```

Ruby version: ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [x86_64-darwin21]

**Comment by jfelchner** [comment]
I have no idea.  I would suggest taking the most basic example from the README/wiki and starting from there.  If there's a problem here, it's almost certainly an issue with your code/setup and nothing to do with the library.  Also, for the record, using progressbar with `puts` is going to cause you problems.
