### ISSUE TITLE
ProgressBar is whiny

### ISSUE THREAD

**Issue by robmathews** [jfelchner/ruby-progressbar#182]
**Current** Problem
--------------------------------------------------------------------------------

 WARNING: Your progress bar is currently at 5152 out of 5152 and cannot be incremented. In v2.0.0 this will become a ProgressBar::InvalidProgressError.

Potential Solution or New Behavior
--------------------------------------------------------------------------------

Please don't have the progress bar potentially stop progress of my task for a *very trivial* error
### Mockups

You are just a progressbar. Don't be whiny.

**Comment by jfelchner** [comment]
I believe the solution to stopping the "trivial error" is to stop doing the trivial thing causing it?
