### ISSUE TITLE
Pass ProgressBar instance to with_progressbar

### ISSUE THREAD

**Issue by d4rky-pl** [jfelchner/ruby-progressbar#185]
Current Problem
--------------------------------------------------------------------------------

When we're using the refinement for `with_progressbar` we cannot access the `ProgressBar` instance. This means we can't use `progress.log`.

Potential Solution or New Behavior
--------------------------------------------------------------------------------

Pass ProgressBar as either the last positional argument to the block or a keyword argument. This behaviour should be optional as to not break existing code.

### Mockups

```ruby
using ProgressBar::Refinements::Enumerator

# I'm really bad at naming things in the morning
User.in_batches.with_progressbar(block_argument: true) do |user, progress|
  progress.log "Unable to do things with #{user.id}" if user.deleted?
  # ...
end
```

**Comment by jsimpson523** [comment]
[Issue 184](https://github.com/jfelchner/ruby-progressbar/issues/184) is essentially asking for the same feature to be implemented.

+1 this feature request

**Comment by jfelchner** [comment]
Fair!

**Comment by jfelchner** [comment]
@d4rky-pl @jsimpson523 If you want to take a look at this and give it a try, if it works, I'll merge it in for you!

@ronen not sure if you're still around but do you want to give this a look?  Thanks!

https://github.com/jfelchner/ruby-progressbar/pull/188/commits

**Comment by jfelchner** [comment]
Moving discussion over to #188

**Comment by jfelchner** [comment]
@d4rky-pl @jsimpson523 I have a beta release out with these changes.  Please check it out and see if it resolves your issues.  You will need to manually require it with:

```ruby
gem 'ruby-progressbar', '~> 1.13.0rc1'
```

in your `Gemfile` because it is a pre-release version.

**Comment by d4rky-pl** [comment]
@jfelchner apologies but I won't be able to test the changes, the project I used this library for is already closed (it was a time limited thing) and I'm too overworked recently to write something new to test it

**Comment by ronen** [comment]
> @ronen not sure if you're still around but do you want to give this a look? Thanks!
> 
> https://github.com/jfelchner/ruby-progressbar/pull/188/commits

Hi @jfelchner, I still exist but sadly I haven't been using Ruby in long enough to comment intelligently.   Passing the progressbar instance certainly makes sense (dunno why I didn't think of that originally!).  And if it passes all the tests, then seems good to me :)

**Comment by jfelchner** [comment]
@d4rky-pl @ronen No worries!  Thank you both!

**Comment by jsimpson523** [comment]
Apologies for the radio silence.

I have gotten back to the point in my project where ruby-progressbar is useful, and am happy to report that the initial experience with `1.13.0rc1` is very positive. This was exactly what I was looking for!

Is this feature still only on a beta branch, or has it been merged into any official releases?

**Comment by jfelchner** [comment]
It's released to stable :)
