### ISSUE TITLE
uninitialized constant ProgressBar::Base::Timer

### ISSUE THREAD

**Issue by Lykos** [jfelchner/ruby-progressbar#190]
Current Behavior
--------------------------------------------------------------------------------
/home/REDACTED/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/ruby-progressbar-1.11.0/lib/ruby-progressbar/base.rb:21:in `initialize': uninitialized constant ProgressBar::Base::Timer (NameError)

### Steps to Reproduce

1. Start irb
2. Write `require 'progressbar'`
3. Write `ProgressBar.create`

### Screenshot

Expected Behavior
--------------------------------------------------------------------------------
This should create a progress bar

Environment
--------------------------------------------------------------------------------

  * Device: Desktop computer

  * OS:

    * [ ] Windows
    * [ ] macOS
    * [ ] iOS
    * [ ] Android
    * [x] Linux
    * [ ] Other

  * OS Version: 22.04
  * Gem Version: 1.13

**Comment by jfelchner** [comment]
`require 'ruby-progressbar'`

**Comment by jfelchner** [comment]
I do also maintain `progressbar` and it is effectively the same gem, but based on your log line, that is not the gem you have installed. 😉

**Comment by Lykos** [comment]
Ooh, ok, sorry for that. I understood 'progressbar' and 'ruby-progressbar' are equivalent, but I guess I still need to make sure I require the same that I install.

**Comment by jfelchner** [comment]
On the off chance people have both installed and on different versions, I want to make sure it works properly for both of them.  Glad you got it sorted out!
