### ISSUE TITLE
Format time including number of days.

### ISSUE THREAD

**Issue by c4lliope** [jfelchner/ruby-progressbar#191]
Current Problem
--------------------------------------------------------------------------------

Here's a progressbar on my screen:

```
#116: |====                                                        |  7.90% ( 1312 / 16601 )  ETA: 216:58:40
```

Potential Solution or New Behavior
--------------------------------------------------------------------------------

I'm hoping I can see the number of days remaining in the ETA, rather than hours.

### Mockups

```
#116: |====                                                      |  7.90% ( 1312 / 16601 )  ETA: 9d 00:58:40
```

**Comment by jfelchner** [comment]
There is a neverending amount of preference around how the time should be displayed.  I've stopped adding any more time preferences for the time being.  Sorry!
