### ISSUE TITLE
Remove progress after 100% complete

### ISSUE THREAD

**Issue by deyman12** [jfelchner/ruby-progressbar#194]
i thought this was a duplicate, in issue #173, but when i added `:autofinish => true`, it didn't work at all. so, are there any other options to clean up the progress when it's already completed to 100%?

![Screenshot from 2024-03-01 19-58-51](https://github.com/jfelchner/ruby-progressbar/assets/128112289/e3fab16b-3dfc-4343-abcf-9934e7bf789b)

the simple code: 
```
require "ruby-progressbar"

p = ProgressBar.create(
  :total => 10,
  :format => "%a %b\u{15E7}%i %p%% %t",
  :progress_mark => ' ',
  :remainder_mark => "\u{FF65}",
  :autofinish => true
)

10.times {
  p.increment
  sleep 0.1
}
```
regards!

**Comment by jfelchner** [comment]
@deyman12 you can set `autofinish` to `false` and then call `p.clear`
