### ISSUE TITLE
Calculate the ETA based on the last N increment or last X seconds

### ISSUE THREAD

**Issue by alessiosavi** [jfelchner/ruby-progressbar#195]
Current Problem
--------------------------------------------------------------------------------
Suppose that you have a loop where the 99% of the work is done in few seconds, and suddenly the last iterations will take a lot of time like the following image (note the 12h already processed)
<img width="1493" alt="image" src="https://github.com/jfelchner/ruby-progressbar/assets/31842468/8de111f5-04fc-4e8e-8962-92a2a8ae073c">

In this case, the calculation of ETA (that seems directly related to `it/s`) will be distorted.

Potential Solution or New Behavior
--------------------------------------------------------------------------------

Use a default `N` parameter in order to calculate the `it/s` and `ETA` taking care about the last `N` iteration instead of starting from the first increment.

Note:
I'me very new to `Ruby`, can't contribute much 🙅

**Comment by jfelchner** [comment]
@alessiosavi we've already had this suggested previously. I'm open to having someone submit a PR for it but won't be adding this myself. Apologies!
