### ISSUE TITLE
compatibility with parallel gem

### ISSUE THREAD

**Issue by dorianmariecom** [jfelchner/ruby-progressbar#196]
Current Behavior
--------------------------------------------------------------------------------

the progress bar acts randomly, doesn't finish, doesn't increment correctly

### Steps to Reproduce

```
require 'parallel'; require 'ruby-progressbar'; progress_bar = ProgressBar.create; Parallel.each(1..100) { |i| sleep(rand(2)); progress_bar.increment }
```

### Screenshot

https://github.com/user-attachments/assets/b10028ac-9a1e-4197-8244-50c976c3ce9b

Expected Behavior
--------------------------------------------------------------------------------

progress bar acts normal, increments, etc.

Environment
--------------------------------------------------------------------------------

![Screenshot 2024-09-01 at 13 32 21](https://github.com/user-attachments/assets/2e3d6711-f1b9-436c-8ecb-c837293ffca4)

  * Device: Macbook Air

  * OS:

    * [ ] Windows
    * [x] macOS
    * [ ] iOS
    * [ ] Android
    * [ ] Linux
    * [ ] Other

  * OS Version: macos 14.6.1

  * Browser:

    * [x] Chrome
    * [ ] Safari
    * [ ] Firefox
    * [ ] Internet Explorer
    * [ ] Edge
    * [ ] Opera

  * Browser Version: 128.0.6613.84 (Official Build) (arm64)

**Comment by dorianmariecom** [comment]
works with threads, not with processes

**Comment by jfelchner** [comment]
Yeah a process is a completely different process so you'd need a progressbar instance defined for each process.  However even then, you can only show one progressbar on the screen at a time.  I think what you're wanting is to have one progressbar that is able to be incremented in each process and that's not possible.

Please let me know if I'm misunderstanding what you're doing but I'm going to close this
