### ISSUE TITLE
Abysmally Slow Performance

### ISSUE THREAD

**Issue by sallustfire** [jfelchner/ruby-progressbar#20]
I've been using the pre-1.0 versions of this gem for a few months now, and have been completely satisfied with.  However, I recently upgraded to v1.0.1 only to discover that the new progress bar is prohibitively slow with the default settings compared to the previous versions.

After profiling a simple loop reading over a 1000 line file,

```
result = RubyProf.profile do
   pbar = ProgressBar.new("Parsing File", 1000, STDOUT)
    File.open('test.txt') do |f|
      f.each do |line|
        pbar.inc
       end
     end
   end

printer = RubyProf::GraphHtmlPrinter.new(result)
printer.print(File.open('test.html', 'w'), :min_percent=>0)  
```

I found that v1.0.1 performed 29.46 times slower.  Of course this includes the deprecations warnings, but the profiling shows that those contributions are minimal at best.  

A quick glance through the profiling results (https://gist.github.com/3693262 - I only had the results as html, you can download the raw contents to view them in a browser) shows that the 1.0 version repeatedly has to recalculate the terminal width.  I don't have the time to figure out how to best fix this.  Maybe it's a simple as a configuration variable?  I tried explicitly setting the length of the progress bar to 80 and did recover some performance, but it was still multiple times slower than the pre-1.0 versions.  

Anyway, I hope this can be fixed.  For the moment, I will have to revert back, because parsing a 100k+ line file is now unnecessarily slow.

**Comment by gurgeous** [comment]
This is still an issue. When running with spring (https://github.com/rails/spring), adding a progress bar to my loop slows it down by a factor of 50x. My ten second method ended up taking eight minutes! This took me a long time to debug.

If I set length manually the problem goes away. I recommend that if IO.console is nil (as it is with spring) we only calculate the length once.

Thanks for creating such a great library!
