### ISSUE TITLE
Enumerable

### ISSUE THREAD

**Issue by gurgeous** [jfelchner/ruby-progressbar#58]
It would be great to mix ruby-progressbar into Enumerable. @toy's gem has a nicely designed mixin:

https://github.com/toy/progress/blob/master/lib/progress/with_progress.rb

I saw in an earlier issue that you were (rightly) worried about threading, pollution, etc. Those are all valid concerns, but this feature is incredibly useful. Perhaps it could be optional?

Possible format:

``` ruby
1.upto(1000).pb.each { ... }
1.upto(1000).pb(title: "factoring").map { ... }
```

We've adapted @toy's mixin for use with ruby-progressbar. We use it on Enumerable and Moped::Cursor. Let me know if you want to take a look.

**Comment by jfelchner** [comment]
@gurgeous now that refinements are a thing, I'm more open to this.  Enumerable support will be added in v1.9.

You can mix in with `using ProgressBar::Refinements::Enumerator` at which point you can use something like:

```ruby
(0...100).with_progressbar do |index|
  # Do stuff
  # Each loop will increment the bar by `1`
end
```

**Comment by gurgeous** [comment]
Neat. I'll check it out when I get a chance.
