### ISSUE TITLE
Prefix Percentage with Spaces To Pad Single and Double-Digit Values

### ISSUE THREAD

**Issue by Undistraction** [jfelchner/ruby-progressbar#77]
Would be great to have a flag for percentage which zero-pads the numbers when in single and double figures so that anything to the right of it isn't pushed out.

Currently:

```
0% | ------------------ | 
12% | ----------------- | 
100%  | --------------- | 
```

Ideal:

```
  0% | ------------------ | 
 12% | ------------------ | 
100% | ------------------ | 
```

The same could also work for total items and completed items.

**Comment by codyrobbins** [comment]
@jfelchner Would it be similarly easy to add variations for `%c`/`%C` as well by any chance?

**Comment by jfelchner** [comment]
@codyrobbins if I start going further down this road, I'm probably going to implement something more akin to a `printf` syntax so that we don't need to keep adding a ton of `%` options.  Feel free to open an issue, but it's going to be a bit before I get to it.
