### ISSUE TITLE
Ruby Gems stuck on 1.7.1

### ISSUE THREAD

**Issue by michaelachrisco** [jfelchner/ruby-progressbar#95]
I am using Rubocop and getting a bundle error on travis: 
```
$ bundle install --jobs=3 --retry=3 --deployment
Fetching source index from https://rubygems.org/
Could not find ruby-progressbar-1.7.4 in any of the sources
```
Looked at my Gemfile.lock and found:
```
    rubocop (0.29.1)
      astrolabe (~> 1.3)
      parser (>= 2.2.0.1, < 3.0)
      powerpack (~> 0.1)
      rainbow (>= 1.99.1, < 3.0)
      ruby-progressbar (~> 1.4)
    ruby-progressbar (1.7.4)
```
And when I go to rubygems: 
https://rubygems.org/gems/ruby-progressbar
Looks like the version is stuck at 1.7.1

I can of course lock my version of the gem within my Gemfile to fix the issue. Just wanted to report the issue.

**Comment by jfelchner** [comment]
Some versions accidentally got pushed last night and were immediately yanked. Just "bundle update rubocop ruby-progressbar" should fix it.
