### ISSUE TITLE
Version 1.7.4 not on Rubygems

### ISSUE THREAD

**Issue by ross-nordstrom** [jfelchner/ruby-progressbar#96]
I have new builds failing today because another package (rails_best_practices) is referencing ruby-progessbar v1.7.4, but it isn't available on Rubygems. 

Can the new versions from today be released to Rubygems?

**Comment by jfelchner** [comment]
There is no 1.7.4. It was yanked. You need to bundle update both gems and that will set your Gemfile.lock properly.

**Comment by ross-nordstrom** [comment]
Thanks
