### ISSUE TITLE
Version 1.7.4

### ISSUE THREAD

**Issue by stefanvermaas** [jfelchner/ruby-progressbar#97]
Hi there,

Could you push the new version of the `ruby-progressbar` to rubygems? 

Cheers.

**Comment by jfelchner** [comment]
Just `bundle update ruby-progressbar`

**Comment by stefanvermaas** [comment]
Travis still can't find the new 1.7.4 version.

**Comment by jfelchner** [comment]
There is no `1.7.4` version.  It was yanked about 10 minutes after it was released.

It's basic bundler Gemfile maintenance.  You need to figure out which gem is depending on ruby-progressbar and update it.  You should be on `ruby-progressbar` version `1.7.1`.

I'm going to be releasing `1.7.5` in a second so you may just want to wait for that.

**Comment by stefanvermaas** [comment]
It was Fuurbar that depended on version 1.7.4 (actually >1.4), so I guess I `bundle updated` in that 10 minute time period. Thanks anyway.
