### ISSUE TITLE
license question

### ISSUE THREAD

**Issue by 375gnu** [jfelchner/ruby-progressbar#99]
Hi, you distribute gem under MIT license, but original gem had ruby license (ruby or gpl2). Was it properly relicensed, i.e. was it sanctioned by Satoru Takabayashi? I want to package it for Debian and it 's very strict in such questions.

**Comment by jfelchner** [comment]
@375gnu the gem was 100% rewritten for version 1.0. As of 1.0 it is MIT licensed.

**Comment by 375gnu** [comment]
okay, thanks for info
